---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: logging-golang
  labels:
    app: logging-golang
spec:
  replicas: 2
  selector:
    matchLabels:
      app: logging-golang
  template:
    metadata:
      labels:
        app: logging-golang
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: logging-golang
          image: umeshkumhar/logging-golang:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 50m
              memory: 50Mi
            limits:
              cpu: 50m
              memory: 50Mi