---
apiVersion: v1
kind: Service
metadata:
  name: logging-golang-service
spec:
  selector:
    app: logging-golang
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP